package com.instantaxtion.zombiesandbox;

/** The in-game patch notes log, newest version first. */
final class PatchNotes {
    static final String VERSION = "9.1";
    static final int VERSION_CODE = 31;

    /** Each entry: a heading, then one line per change. */
    static final String[][] NOTES = {
            {
                    "9.1  -  Bridges, bigger services, a sharper map",
                    "The railway crosses the highway on a bridge: highway traffic runs straight underneath and never meets a train (no more pile-ups at the tracks).",
                    "More police, firefighters and medics, growing with the city: more officers for every resident, an extra police station on Large maps and two on Massive ones, more fire stations on big maps with five firefighters each, and medics at the hospital and the fire stations (every town has a fire station now).",
                    "The map stays sharp when you zoom in: the area on screen is drawn again in fine detail a moment after you zoom.",
            },
            {
                    "9.0  -  The city reacts",
                    "People act like it's the apocalypse: word of the outbreak spreads (first reports, then an emergency broadcast), and anyone who sees one or hears gunfire knows at once. They drop their day and hurry home, to a safe zone, into the nearest building or to the police station. People indoors stay in. Drivers flee town and no new traffic comes in. The all-clear comes once it's over.",
                    "Most police patrol in cars, two to a car, lights off, keeping to the rules of the road. The nearest car answers each 911 call with lights and siren; officers get out at the scene and drive on once it's quiet.",
                    "Firefighters really drive their fire engine: it waits at the station until a crew climbs aboard, they get down at the fire, climb back on when it's out and drive home.",
                    "Highways: wherever there's countryside round the town, a divided highway crosses the map (three lanes each way, a barrier, route shields, green signs, lights where roads from town join). Highway patrol drives it, and in the USA sheriff's deputies patrol the country roads.",
                    "The cure is gone. A bite is for good; medics still heal wounds.",
                    "Zombies at a building with people hiding find their way to the door and batter it together instead of getting stuck on the walls. They leave empty and abandoned vehicles alone, and car alarms don't keep them milling about.",
                    "Easier to follow: zoomed out, everyone is a dot in their side's colour and the ground glows red where the dead gather. Map labels no longer pile on top of each other. Announcements queue in one band, and the radio, the war meter and the air strike countdown each have their own place. The stats shrink to one line when the outbreak starts.",
                    "Roads: worn wheel tracks, white edge lines, bolder lane lines and wide zebra crossings.",
            },
            {
                    "8.0  -  Bigger cities, real buildings",
                    "Every map is twice the size it was, so buildings can be built at real-world scale: long terraces, deep office blocks, big-box stores, hospitals and stadiums.",
                    "159 kinds of building, each with its own roof, colours and sign, chosen by country and by district: diners, drive-thrus and motels in the USA, corner pubs, milk bars and Queenslanders in Australia, konbini, izakayas, pachinko parlours and ryokan in Japan, boulangeries, brasseries and Haussmann blocks in France, taquerías, tortillerías and paleterías in Mexico, plus towers, halls, factories and homes everywhere.",
                    "Real floor plans inside: rooms with walls and doorways, furniture to suit each place (sofas and beds at home, desks in offices, shelves and tills in shops, beds on the wards). People inside keep apart at their own spots and walk between rooms through the doors; when a building is full, the rest are upstairs.",
                    "Streets line up: side streets carry straight on across junctions, and a narrow street meets the middle of a wide one.",
                    "Cars keep to their own lane right up to the junction and turn inside it, slow down for corners, no longer swerve across the lanes or spin round in the road, and run red lights far less often. There's more traffic on the bigger maps. Parked cars stay off narrow streets and back from junctions.",
                    "People out for a walk no longer pace back and forth; they carry on or turn along the pavement. Police, soldiers and medics keep to the pavements and crossings unless they're on a call.",
                    "Basketball and tennis courts and football pitches have proper markings at the right size, inside the court.",
            },
            {
                    "7.3  -  Everyone has a life",
                    "Every resident has a life of their own: office and warehouse workers, nurses, teachers and cashiers who commute to a real workplace and stay a shift; shopkeepers who run a shop; students who go to school; people who mostly stay home; people always out on errands; joggers; park-lovers and dog walkers; a postal worker doing rounds house to house; street food vendors with their carts at the plazas.",
                    "The day is under way when the game starts: many people are at home or at work indoors, and the rest are out doing their thing.",
                    "Neighbours stop and chat in the street.",
                    "Tap someone to see their life and what they're doing (\"Nurse at City Hospital, lives on Oak St\" - \"On the way to work\"). Tap a building to see who's inside: at home, at work or visiting.",
            },
            {
                    "7.2  -  Traffic that follows the rules",
                    "Traffic lights at the big junctions, cycling green, amber and red each way (shown on the corners). Cars stop at the line on red, stop on amber unless it's too late, and go on green.",
                    "Stop junctions: STOP (ALTO in Mexico) painted on the road and signs on the corners. Cars come to a full stop, then go when the junction is clear. Roundabouts: give way to anything already on it.",
                    "Cars drive in the middle of their own lane, on the right (on the left in Australia and Japan), including on avenues with a median, and only steer while they're moving.",
                    "Everyday traffic stays on the roads instead of cutting across pavements and car parks.",
                    "Cars no longer vanish. A car that can't find anywhere to go pulls in and parks; parked cars and wrecks are only towed away, and new traffic only turns up, where you can't see.",
            },
            {
                    "7.1  -  Buildings, cars and lanes for every country",
                    "Buildings built the local way. Australia: hip roofs in Colorbond or tile, verandahs, solar panels and rainwater tanks. Japan: kawara-tiled roofs, temples, green-roofed shrines and pagodas, flat-roofed blocks crowded with air conditioners, water tanks and balconies on every floor. France: zinc mansard roofs with dormers and chimney pots, tall windows and wrought-iron balconies, cathedrals with spires. Mexico: flat roofs behind painted parapets with black water tanks and rebar for the next floor, roof terraces, barred windows and tiled church domes with twin bell towers.",
                    "Signs in the local language: POMPIERS, ÉCOLE and MARCHÉ in France; POLICÍA, BOMBEROS and MERCADO in Mexico; PETROL in Australia; KOBAN in Japan.",
                    "Traffic that fits the country: pickups, SUVs, yellow cabs and school buses in the USA; utes and 4WDs in Australia; tiny kei cars and minivans in Japan; hatchbacks and vans in France; Beetles, pickups and pink-and-white taxis in Mexico. Each kind of car looks different from above.",
                    "Turn lanes: arrows on the avenues before each junction, inner lane for turning across the traffic, kerb lane for straight on or turning off, painted on the side of the road the country drives on.",
                    "Safe zones can no longer be placed by hand. The police and army decide where and when they go up.",
            },
            {
                    "7.0  -  Countries, safe zones and city life",
                    "Countries: pick USA, Australia, Japan, France or Mexico on the New Game screen. Each has its own buildings and colours, pavements, street, town and people's names, road lines and police cars. In Australia and Japan traffic drives on the left. The country is part of the city code.",
                    "Safe zones reworked: they're never set up near the dead, take time to build (the guards arrive and the sandbags go up section by section; it opens when they're done), and their border is a living line that grows as people arrive and guards join, stops at walls and pulls back where the dead push. Lose too much ground and the zone falls.",
                    "Pedestrians follow the rules: they keep to the pavement, cross at the zebra crossings (now at every junction) and wait at the kerb for cars. Running for your life is the exception.",
                    "Roads make more sense: bigger blocks, streets that carry on straight across junctions, medians only on long avenues and open wherever a side street joins.",
                    "Fire stations, police stations, the hospital and the base are spread across town instead of next to each other.",
                    "Everyone who lives in the city is out and about by default, and the number of police and soldiers is set by the size of the city. The Cops and Military options are gone.",
                    "Each Reinforcements setting now says exactly who comes: how many waves of police backup, army squads, tanks and helicopter sorties.",
                    "The civilian count no longer jumps around as people go in and out of buildings, and the People row on the New Game screen fits on tall phone screens.",
                    "Removed: the Orders, Place, Events and Build tools, and evacuation trains (trains still run).",
            },
            {
                    "6.0  -  Twenty changes",
                    "1. Drive anything. While you control someone, Get in a car, cruiser, truck, ambulance, fire engine or tank. Steer with the stick (pull back to reverse), sound the horn or siren (it draws the dead), fire the tank's cannon, run zombies over. Crashes damage the vehicle; your group rides with you.",
                    "2. Weapons. Walk over a gun, bat or axe to pick it up or swap. Shotguns are deadly up close, rifles fire in bursts, bats stun, axes kill. Bats lie near houses, axes wait at fire stations, the fallen drop their guns, gun stores sell shotguns. Soldiers get a Grenade button.",
                    "3. Go inside buildings: hide, Barricade the door, and Search once for food, medicine, shells or a pistol in a drawer (or something waiting in the dark).",
                    "4. Rally: up to eight nearby civilians follow you, into cars and buildings too.",
                    "5. The race for a cure. While the hospital holds, doctors work on a cure (bar under the war meter). When it's ready, every bitten person is saved, medics bring zombies back to life, and shots sometimes do too. A third way for the war to end.",
                    "6. Escalation. When the city is being lost, the army seals off the worst district (barricades on every road out), and later announces an air strike with a 60-second countdown before firebombing it.",
                    "7. Ammo runs out. Precincts and the base have limited armouries, safe zones keep their own stock, and army supply trucks carry ammo to zones that run low. Trucks can be lost.",
                    "8. Fire spreads. Burning cars and blasts set buildings alight; fires grow, jump next door and burn buildings down unless fire engines put them out.",
                    "9. Militias: armed residents band together, take over a building, hold the street and shelter their neighbours.",
                    "10. Stampedes: panicking crowds knock people down. Groups that stick together don't.",
                    "11. Hordes travel the lanes between the town and the hamlets on big maps.",
                    "12. Brutes charge (bowling people over, smashing barricades and cars), crawlers lie in wait by cars and in the grass, and screamers bring the dead to gunfire.",
                    "13. Deer and foxes in the countryside. Deer bolting from the woods means something is coming; a caught fox can come back as a zombie dog.",
                    "14. Noise rings show how far gunfire, alarms, horns and screams carry.",
                    "15. Who bit whom: cards show who bit someone and how many each zombie has turned; Stats shows the chain from patient zero. Zombies keep the name of the person they were.",
                    "16. Highlights: the big moments are marked on the replay's timeline; tap near one to jump to it.",
                    "17. Pins: star someone on their card; off screen they get a marker at the edge (tap to jump), and the pin follows them if they turn.",
                    "18. City editor: the Build tool paints roads, pavement, grass, trees and walls and puts up houses and shops (Clear knocks one down). Edits go into the city code, so sharing the code shares your city, and saves keep them.",
                    "19. Faster big cities: calm people far from any zombie make their decisions a third as often. The busiest test city needs about 40% less time per step.",
                    "20. Feel: vibration when you shoot, get hurt, crash or a blast goes off nearby (Settings: Vibration), and bodies are thrown by blasts, cars and charging brutes.",
                    "Fixed: a car pulled over against the kerb couldn't be driven away.",
            },
            {
                    "5.4  -  Take control",
                    "New: Take control of anyone. Tap someone with Move and press Take control on their card: a civilian, cop, soldier, medic, firefighter, raider, dog or even a zombie. Put your left thumb down anywhere on the left to walk (push further to run; the living get out of breath), and hold the red button to act. Armed people auto-aim at the zombie most in line with where they're facing, zombies bite, and everyone else shoves. The camera stays with them and their health and ammo are shown. Stop controlling (or picking another tool) hands them back to the AI; if they die, that's that.",
                    "New: Outbreak replay. The Replay button on the Stats screen plays the whole game back on the city map: people in blue, the dead in green, and a red mark wherever someone turned (fresh ones bright). Watch the infection spread street by street, or drag the timeline to any moment. Saved games keep their replay.",
            },
            {
                    "5.3  -  Crowds",
                    "No more limit of 800 people: a city has as many people as its homes hold, so a big city has thousands. The Max population setting has a new default, Auto, which makes room for everyone who lives in the city (and plenty of zombies). You can still pick a fixed limit.",
                    "The simulation is about twice as fast with big crowds: looking for zombies no longer checks every person nearby, and people only bump into those they could actually touch.",
                    "People go inside on errands: into shops, the supermarket, pharmacies, churches, schools and their own homes, stay a while, and come back out. Busy places put people off, and a full place is skipped rather than queued at, so crowds no longer pile up at doors. If zombies turn up outside, the people inside stay in and shelter. The building card shows who's inside.",
                    "People who are at home when the game starts are indoors, and come out a few at a time.",
                    "Families go about together in groups of 1 to 5 (a whole apartment block no longer walks around as one family).",
                    "Less getting stuck on buildings: everyone looks a step ahead, and turns to walk along a wall or round a corner instead of pushing into it. Many more routes are planned each second, so people in big crowds find their way instead of heading straight for a wall.",
                    "Fairer fights: both sides have the same senses. The dead can smell the living a few streets away, not from across town, and police and soldiers only spot distant zombies in front of them (anything close, they notice all round). In simulated wars, 50 zombies now win about 3 games in 5 instead of 4 in 5, and 20 zombies about 1 in 3, as before.",
                    "Fixed: people leaving a building when the population limit was full could vanish.",
            },
            {
                    "5.2.1  -  Trees",
                    "Fixed: people and zombies got stuck between trees, in the woods and beside street trees. A tree now only blocks the way at its trunk, so everyone can slip between trees and round them, and anyone who walks straight into a trunk steps off to one side.",
            },
            {
                    "5.2  -  Homes, towns and trains",
                    "Everyone lives somewhere. Each house has a family of 1 to 5, apartment blocks have two people to a flat on every floor, and some offices and shops have flats upstairs. How many people a city has now comes from its homes, and the People option chooses how many of them are out and about (None, Few, Some, Most or All). New Game shows how many people the city's homes hold.",
                    "People start at or near their own homes (some are out on errands, some out together as a family with the dog), and run home first when trouble starts.",
                    "Towns out in the country (every Massive map, and small towns) are no longer a square: they grow a ragged, organic outline with roads running off into the fields. Blocks that only stray roads reached are gone.",
                    "Hamlets: small clusters of cottages on a short street out in the country, each with its own name and a lane back to town.",
                    "Railways: streets are carried across the line so the town isn't cut in two, with a level crossing every so often. Country lanes cross the tracks too.",
                    "Level crossings have barriers and flashing red lights that come down while a train is near (and stay up otherwise).",
                    "Trains slow down and stop at the station for a few seconds, and commuters get off and on.",
                    "Evacuation trains: during an outbreak, trains wait at the station for 25 seconds. People nearby run for the platform, and everyone who gets on is safe. A train won't stop if zombies are on the platform. The Stats screen counts how many got away.",
                    "Air support is realistic: once it's approved, the crew has to be briefed and the aircraft readied (about a minute from a helipad in town, nearly two if it's coming from outside the city), and the radio gives an ETA. The helicopter spins up for 16 seconds, climbs out slowly, slows for its approach, flies a wide orbit so the door gunner can fire short bursts, and heads home after about 45 seconds on station. Helicopters from outside the city are heard before they're seen.",
                    "Fixed: old saves with more than 5 People settings are read correctly.",
            },
            {
                    "5.1  -  Guard, firefighters and the countryside",
                    "National Guard: when the army has no reserve squads left and the war is going badly, the Governor calls out the Guard. Two trucks of guardsmen (tough, well stocked, olive drab) drive in from the edge of the map and reinforce the safe zones. You can also place them yourself from the Military picker.",
                    "Firefighters are a real unit now. Three wait at each fire station and more ride out on fire engines. They hose down fires, give first aid to hurt people nearby, fight zombies off with an axe and back away from crowds.",
                    "Simpler spawn menu: fewer buttons (People, Police, Military, Zombies). Buttons with a dot open a picker that shows every choice with a one-line description. Tap one and tap the city.",
                    "New map size: Massive. The city sits in open country, with room to spare.",
                    "Countryside: villages, small towns and massive maps are surrounded by fields, woods, winding dirt lanes out to the edge of the map, and farms and lonely cabins along them.",
                    "Villages are villages: a high street, a crossroad and a back lane with cottages in gardens, instead of a grid of city blocks.",
                    "Not every map has a train any more. Industrial and Metropolis always do, Classic and Small Town sometimes, the others never.",
                    "Roadblocks are realistic: police cars drive from the nearest precinct to the roads leading into a safe zone, park across the road with cones and an officer on guard, and drive home when the zone closes. No more cars appearing out of nowhere.",
                    "Fixed: safe zones never closed. A zone now packs up when it has been quiet for a while or empty for 90 seconds, and quickly once the outbreak is over.",
                    "Fixed: the Military button could cycle to police roles.",
                    "Fixed: name tags piled on top of each other in crowds, and the radio feed could overlap the win meter on a phone held upright.",
                    "Fixed: roadblock officers were saved as ordinary cops and stood at their posts forever after loading, and Guard trucks lost their guardsmen when saved.",
                    "Fixed: new people types could have been counted as zombies.",
            },
            {
                    "5.0  -  Who will win?",
                    "(Games saved in older versions can't be loaded, because cities are built differently now.)",
                    "Districts: every city is made of named neighbourhoods, each with its own character. Downtown has small blocks of glass towers on a grid; the Old Town has wandering streets of brick terraces with shops and courtyards; the suburbs sprawl with houses; industrial estates have big warehouse yards; the University District has halls on lawns; parkside districts are green. Zoom out to see their names.",
                    "Buildings do things. Every building has food, and survivors hiding inside eat it. When it runs out they have to go out and find more. Gun stores arm frightened people until they're cleaned out. If the power station is overrun there's a blackout: no sirens, and nobody hears about safe zones any more. If the hospital falls, nobody can be treated. Both come back once they're cleared.",
                    "Tap a building (with Move) to see what it is, its district, who's inside, its food, ammo or medicine, and what it does for the city.",
                    "New interiors: zoom right in to see inside. Houses have kitchens, sofas, beds and baths; offices have desks and screens; supermarkets and the mall have aisles; the hospital has wards; the police station has cells; schools have classrooms; diners have booths; gun stores have racks. Looted and smashed places are wrecked inside.",
                    "Zombies in the buildings: some are shut inside, waiting. Nobody knows until someone opens the door, or until they burst out. Idle zombies wander into empty buildings to lurk, put in shop windows, and set off car alarms that draw every zombie for streets around. When a shelter is overrun, some people don't get out.",
                    "Every outbreak is a different strain, with hidden traits found out over the radio: fast- or slow-acting, virulent or weak bites, tough or frail zombies, swift ones, keen or dull senses, or the dead rising even without a bite. How ready the city was is revealed too: unprepared, panicking, a gun town, or well prepared.",
                    "The war can go either way now. People tire when they sprint (the dead never do), body shots only wear a zombie down while headshots drop it, police and soldiers can be overwhelmed, and hunger draws the dead from right across town. A small outbreak is usually contained, but not always; a big one is anyone's guess.",
                    "A tug-of-war bar under the stats shows which side is winning. Banners mark the turning points and the end: \"The city survives\" or \"The city has fallen\". The Stats screen shows the strain and what's known about it.",
                    "Heroes call out their kills on the radio at 10, 25, 50 and 100.",
                    "Fixed: spitters and bloaters weren't counted as zombies, so an outbreak could end with them still around.",
            },
            {
                    "4.2  -  Performance",
                    "Fixed the big slowdown from 4.0: people's daily errands were working out a brand new route across the whole city almost every frame. They now visit a set of popular places whose routes are remembered, and only a few new routes are planned each second. The simulation runs about 15 times faster in a busy city.",
                    "On a slow phone, high game speeds now run a little slower instead of making every frame take longer and longer.",
                    "Far less drawing when zoomed out: windows, legs, hair, soft shadows and shading are only drawn when you're close enough to see them, and vehicles off screen aren't drawn at all.",
                    "The minimap draws its dots a few times a second instead of every frame.",
            },
            {
                    "4.1  -  Realistic graphics",
                    "New Graphics setting: Realistic (the new default) or Classic (the old flat look). It switches straight away, even mid-game.",
                    "Realistic ground: grainy, patched tarmac, raised kerbs with a lit edge and a shadow on the road, paving slabs in slightly different shades, mown stripes on the lawns and more natural colours.",
                    "Soft lighting: buildings darken the ground right around them, their shadows have soft edges, and roofs are weathered with grime, stains and a lit parapet.",
                    "Walls are darker near the ground with a lit cornice along the top, and windows reflect the sky and have sills.",
                    "Leafy tree canopies made of several clumps, shaded underneath and lit on top.",
                    "People are lit from above with soft shadows; cars have a sheen along the roof, darker sides, an outline and wing mirrors.",
                    "The map is smoothed instead of pixelated when you zoom in.",
            },
            {
                    "4.0  -  The big one",
                    "(Games saved in older versions can't be loaded, because cities are built differently now.)",
                    "New zombies: Spitters hang back and lob acid that leaves burning puddles. Bloaters are slow and swollen, and burst into a cloud of infectious gas when they die (police and soldiers try not to shoot them when people are close).",
                    "New police: riot police with shields that turn away most bites from the front, and K9 units (an officer with a police dog). Tap the Cop button again to switch.",
                    "New events: an airstrike (a jet makes a bombing run across the spot you tap), a city alarm (sirens send everyone indoors or to a safe zone) and Infect (someone at that spot is bitten). New Place item: a medkit that patches up anyone nearby and can treat fresh bites.",
                    "Army checkpoints: soldiers check everyone coming into a military safe zone for bites. Most are caught: they are treated in quarantine if a medic is about, otherwise turned away and sent to the hospital.",
                    "Police roadblocks: when the police open a safe zone they park cruisers across the roads leading to it, lights on. They pack up when the zone closes.",
                    "Drag to select: with the Orders tool, drag a box to select a whole group of police and soldiers at once.",
                    "8x speed. Three save slots (plus the autosave) with a Load Game button on the main menu. A Radio Log with every message this game; tap one to go there. Hide Buttons in the pause menu for clean screenshots.",
                    "Name tags setting shows everyone's name. The stats screen graphs police and army numbers too, lists the top killers and where the outbreak started, and Patient Zero is marked on the map.",
                    "The minimap shows where the infection is spreading. Every city has a name.",
                    "Graphics: everything casts shadows the same way, people walk with their legs and have hair, caps and beanies, cars have tyres, brake lights and a glint on the windscreen, trees sway in the breeze, and roofs have solar panels, rooftop gardens and skylights.",
                    "Effects: acid puddles, bloater gas, puffs of dust where bullets hit, a jet with its contrail and shadow, and emergency lights that wash the road red and blue.",
                    "New sounds: the jet, spitting, a bloater bursting, the city alarm and bites glancing off riot shields.",
                    "New in the city: roundabouts, trees along the pavements, back alleys with bins and dumpsters, building sites with a crane, a shopping mall, a football stadium, a power station, a helipad and ambulance bay at the hospital, bandstands and flower beds in parks, and farms on the edge of town.",
                    "Smarter zombies: they see a long way in front of them but only notice what is close behind, remember where they last saw someone and search around there, and their moans draw in other zombies nearby.",
                    "Smarter civilians: everyone has a home. While the city is calm they run errands to the shops, the mall, church or school and go home again; once they hear about the outbreak they head home and lock the door.",
                    "Smarter police and soldiers: they radio sightings to units nearby, move in a wedge behind their leader, advance by bounding (half the squad covers while the other half moves), send flankers round the side for a clear shot, and pull back to a medic when badly hurt. Police form a cordon around the scene of a call.",
                    "Medics do triage: fresh bites first, then the worst hurt. Anyone they cure is pointed to a safe zone.",
            },
            {
                    "3.1  -  Streets, not grids",
                    "Cities are laid out a new way: a few main roads, then each district is split up by its own streets. Streets rarely line up across a main road, so you get offset crossings, T-junctions and blocks of every size instead of a grid. Downtown blocks are small, the suburbs have long ones.",
                    "Block corners are rounded off with wide kerbs, and every street has its own name (lanes, courts, drives and avenues), with a ring road around the edge of town.",
                    "The railway only has level crossings where streets meet it from both sides.",
                    "Fixed: the counts at the top go up straight away when you spawn someone, even while paused.",
                    "Zombies claw at tanks and can knock them out (the crew bails out). Tanks no longer shoot through buildings.",
                    "Fire stations and the hospital don't send anyone out while zombies are at their door.",
                    "People remember where they saw a zombie: civilians keep away from that area for a while, and police and soldiers go and check it out.",
                    "Army trucks and police cars stop short of a big crowd of zombies and let the troops out, instead of driving into it.",
                    "Anyone who gets stuck (brutes at doorways especially) steps aside and tries another way.",
                    "Safe zones stand down after a couple of quiet minutes, or when no one is left to guard them. New zones only open while there are live 911 calls.",
            },
            {
                    "3.0  -  A bigger, truer city",
                    "Bigger maps: Small is now what Medium was, and Large is bigger than ever. (Games saved in older versions can't be loaded, because cities are built differently now.)",
                    "More realistic cities: short blocks downtown and long ones further out, main roads every few streets, an office core ringed by apartments, shops along the main roads, homes on the outskirts and an industrial district on one side of town.",
                    "Suburban cul-de-sacs with houses round a turning circle, and street furniture: benches, bins, fire hydrants, bus stops and traffic lights.",
                    "Railways: a line runs across most maps with level crossings, a station, and trains that pass through (traffic waits for them; anything left on the tracks gets hit).",
                    "Tap anyone to see who they are: their name, job, what they're doing, health, ammo, kills, and who they're with.",
                    "Place tool: drop in a car, a police car, a tank, a fire engine, barricades (drag to build a line; zombies batter them down), a supply crate or a fire.",
                    "Events tool: send a horde in from the edge of town, start a panic, trigger an outbreak inside a building, call a supply drop or bring in a raider gang.",
                    "Undo takes back your last placement or spawn. Clear now asks what to clear: everyone, zombies only, bodies and blood, wrecks and fires, or barricades.",
                    "Raiders: armed gangs who shoot zombies and police, rob armed civilians of their guns and loot shops. Police treat them as a threat. Tap the Civilian button again to spawn them.",
                    "Zombie dogs: dogs killed by zombies can come back as fast, vicious zombie dogs. Fresh zombies are quicker for their first minute, and during a long outbreak the infection evolves and new zombies get tougher.",
                    "Survivors act on their own: families make supply runs to the shops, armed civilians form patrols, and people running for their lives jump into abandoned cars and drive off. Some outbreaks start inside buildings.",
                    "Recovery: once the zombies are gone the city recovers. Volunteers clear away the bodies, buildings are repaired, wrecks are towed and the safe zones close.",
                    "Music follows the action: calm when the streets are quiet, intense in a big fight. New sounds for trains, tanks, machine guns, snipers, collapses, crashes, fire hoses and ambulances.",
                    "Minimap (tap it to jump there) and an Auto cam that follows the most interesting thing going on.",
                    "Screenshots: save a picture of your city from the pause menu and share it.",
                    "Records and achievements, kept across games, in the main menu.",
                    "New settings: text and button size, battery saver and minimap. A new app icon.",
            },
            {
                    "2.4  -  Volunteers",
                    "Recruitment: once the outbreak has cost the police or army people, they put a call out on the radio for volunteers to fill the gaps (only as many as they've lost, and only while the station or base is safe).",
                    "Civilians decide for themselves. Most say no. People who own a gun are keen, and people with family to look after or who are hurt usually refuse. Anyone who says no isn't asked again.",
                    "Volunteers walk to the precinct or base, train for a few seconds and come out as a cop or soldier. Scared volunteers turn back if zombies show up on the way.",
                    "The stats panel and Stats screen show how many joined and how many said no.",
            },
            {
                    "2.3  -  Armor, ambulances and a new setup screen",
                    "New Game screen redesigned: a live preview of the city, map cards with a description of each map, one-tap buttons for every option, and a New map button to reroll the city before you start.",
                    "Two new maps: Metropolis (a huge dense skyline with three precincts and a base) and Village (cottages among fields, far from help).",
                    "New buildings: apartment blocks (rooftop water tanks and washing lines, room for lots of people to hide), parking garages (cars parked on the top deck) and pharmacies (hurt people stop in to patch themselves up).",
                    "New vehicles: tanks roll out of the base for big hordes, shelling crowds and machine-gunning stragglers, and ambulances drive out from the hospital to fetch the badly hurt.",
                    "New military: a commander (beret, pistol and radio) whose soldiers shoot better when he's close and who calls in armor or air support, snipers with long-range scoped rifles, and machine gunners in every squad. Tap the Military button again to pick which one to spawn.",
                    "The helicopter now starts up on the helipad, takes off, drops lower to give its gunner a shot, flies home and lands. It leans into turns and its shadow moves away as it climbs.",
                    "Every vehicle shows what it's doing: responding, carrying a squad, fighting a fire, loading a patient, driving people to safety, broken down and so on.",
                    "Fixed: people hiding in buildings walk around to the door instead of running into the wall.",
                    "Fixed: parked cars stay against the kerb, and cars abandoned in traffic roll over to the side of the road.",
                    "New effects: spent shell cases fly out of guns, muzzle flashes light the ground, explosions throw out debris, tyres leave skid marks, rotor wash kicks up dust, and fire hoses leave puddles.",
                    "New textures: patched and cracked asphalt, manhole covers, worn paving slabs, grass tufts and wildflowers.",
                    "Higher limits: up to 800 civilians, 60 cops, 40 soldiers and 200 zombies at the start, and a max population of up to 6000 in Settings.",
            },
            {
                    "2.2  -  Wrecks, rubble and smarter survivors",
                    "Cars take damage: running over zombies, crashing into each other, gunfire, explosions and zombies clawing at them. Damaged cars smoke and slow down, then break down. Everyone inside gets out, and some wrecks catch fire.",
                    "Fire engines: fire stations send an engine to burning cars and gas pumps. The crew hoses the fire down and pulls out if zombies close in.",
                    "Destructible buildings: bombs, grenades and blasts crack and scorch buildings, and enough of them bring one down in a cloud of dust. Anyone inside or next to it gets hurt.",
                    "Bullet holes and scorch marks build up on walls after a firefight.",
                    "See-through roofs: zoom right in and roofs and walls fade so you can see the rooms, furniture and anyone hiding inside.",
                    "Bird's-eye view: a new View button (and setting) switches between the leaning 3D buildings and a flat view straight down.",
                    "Dogs: people walk their dogs, and dogs bark at zombies and go for them to protect their owner. Tap the Civilian button again to spawn dogs.",
                    "Families and friends walk together, stay together when they run, hide in the same building and pull zombies off each other.",
                    "Traffic: people running for their lives wave down passing cars and jump in. Drivers take them to a safe zone if there is one. Zombies chase cars and swarm the ones that stop.",
                    "Zombie hordes: idle zombies gather behind a leader and roam the city, merging into bigger hordes. The radio warns when a big one is on the move.",
                    "Smarter zombies spread out to surround people and stop to feed on the dead.",
                    "Smarter police and soldiers: they shoot the zombie that is attacking someone (or a runner or screamer) first, hold fire when a person is in the way, don't throw grenades near people, fall back when swarmed or reloading, and soldiers keep their squad together.",
                    "Smarter civilians: panic spreads through a crowd, people run towards nearby cops and soldiers, and armed civilians back off while they shoot.",
                    "Churches, schools and supermarkets can become safe zones. Supermarkets also stock ammo, and armed civilians go there to restock.",
                    "City codes: every city has a code (shown in the pause menu and stats). Use City code on the New Game screen to replay a city or play one a friend shared.",
                    "Burnt-out wrecks, collapsed buildings, damage and families are now kept in saved games.",
                    "Map labels no longer hide under the radio feed or the stats panel.",
            },
            {
                    "2.1  -  A living city",
                    "New buildings: rows of shops with striped awnings, gas stations, churches with steeples and churchyards, schools, fire stations with fire trucks, and supermarkets with big car parks. People can hide in the shops, churches, schools and supermarkets.",
                    "New parks: playgrounds, soccer fields, basketball and tennis courts, community gardens, skateparks and cemeteries.",
                    "New maps: Old Town (narrow streets, shops and churches), Small Town and Campus (schools and sports fields). Every map has its own mix of landmarks and parks.",
                    "Traffic: cars drive around town, brake for pedestrians, plough through zombies, and get abandoned when the driver is surrounded.",
                    "Pigeons in the parks and plazas scatter at gunfire, explosions or anyone walking up, and land somewhere else.",
                    "Fires: explosions set parked cars burning, sometimes blowing up a moment later. Gas pumps go up in a big secondary blast. Wrecks stay charred, and fire hurts anyone standing in it.",
            },
            {
                    "2.0  -  The city fights back",
                    "Police cruisers drive backup officers to incidents and army trucks carry reserve squads out of the base, running over zombies on the way.",
                    "Air support: a helicopter flies from the base helipad and circles the fight with a door gunner. Sorties are limited.",
                    "Civilians barricade themselves in homes, offices and warehouses. Zombies batter the doors down, and people come out once the street is quiet. If someone infected turns inside, the building is lost.",
                    "Guards stand at the police station doors and the base gates.",
                    "Some civilians own a gun, and anyone can pick up a weapon dropped by a fallen cop or soldier.",
                    "Ammo is limited. Units out of ammo radio in and head back to the station or base to resupply.",
                    "Hand-to-hand: anyone can shove a zombie away and stun it, and cops and soldiers hit back with their weapon.",
                    "Medics and a hospital: medics heal the hurt and can cure fresh bites. Badly hurt people walk to the hospital.",
                    "Zombies are drawn to gunfire and explosions. New types: crawlers (hard to hit, and what's left after a blast) and screamers (their shriek calls every zombie nearby).",
                    "Orders tool: tap a cop or soldier (soldiers bring their whole squad), then tap where to send them. Tap them again to release them.",
                    "Save and load: save from the pause menu. The game also saves itself when you leave, and Continue picks it up.",
                    "Stats screen: people vs zombies over time, plus totals.",
                    "How to Play: a short tutorial on the first game, and in the main menu any time.",
                    "The stats panel collapses with a tap, the radio feed is shorter on phones, and people are easier to tell apart when zoomed out.",
                    "The Zombie button covers all zombie types: tap it again to switch.",
            },
            {
                    "1.6  -  Simpler cities",
                    "Water is gone: no more rivers, islands, ponds or fountains. Plazas have statues instead.",
                    "It's always daytime. The sunset and night modes (and the orange haze) are removed.",
                    "The New Game screen is down to 7 options: map, map size, civilians, cops, military, zombies and reinforcements.",
                    "Maps: Classic, Downtown, Suburbs, Industrial and Parkland. Each one decides its own buildings, street layout, parks, police stations and military base.",
            },
            {
                    "1.5  -  Limits",
                    "Safe zones have a capacity: 25 in a park zone, 35 at a police station, 40 for a military zone and 60 at a base. Labels show how full each one is.",
                    "Full zones radio that they're turning people away, and civilians head for a zone with room or keep running.",
                    "Reinforcements are now a small, fixed reserve that never refills. Choose Off, Low, Medium or High on the New Game screen (Medium: 2 backup waves of officers and 2 army squads of 4).",
                    "The stats panel shows the reserves left, and the radio says when the last one is sent.",
                    "Ponds no longer cut through park footpaths.",
                    "Rivers keep a grassy bank: no building stands on or right next to the water.",
            },
            {
                    "1.4  -  Less grid, more city",
                    "New Street layout option: Grid, Varied or Organic.",
                    "Varied and Organic cities merge some blocks into superblocks, so streets have T-junctions and blocks come in different sizes.",
                    "Boulevards: wide avenues with a tree-lined median.",
                    "Rivers now wind across the map instead of running straight. Roads cross on bridges, and riverside buildings make way for parks.",
                    "Islands have a rounded, irregular coastline with beaches. Roads end at the sand.",
                    "Parks can have ponds and curved footpaths.",
                    "Rounded curbs at block corners.",
                    "Police stations: a precinct with parked cruisers. Some cops start there, backup officers leave from there, and police set up their safe zone there first.",
                    "Military bases: a fenced compound with gates, barracks, a helipad, tents, a watchtower and army trucks. Soldiers start on base, squads deploy from its gate, and the base becomes the military safe zone.",
                    "Idle soldiers return to base when there's nothing to fight.",
                    "New Game options for the number of police stations (0-3) and a military base.",
            },
            {
                    "1.3  -  911, radio and safe zones",
                    "911 calls: civilians who spot zombies call it in. Dispatch opens an incident at the nearest street corner and sends the closest free cops.",
                    "Cops report when they're en route, on scene and when the area is clear. Dispatch calls it in when an officer goes down.",
                    "Police and military talk on the radio: big incidents, downed officers or a safe zone under attack make police request military support, and the military sends a squad.",
                    "Reinforcements: if nobody is free, backup officers or a military squad arrive from the edge of the map. Can be turned off on the New Game screen.",
                    "Safe zones: police and military set up guarded zones with sandbags in parks, plazas and parking lots. Guards take posts around the edge and face outward.",
                    "Civilians run to safe zones when they're scared or hear about one on the news, and shelter inside.",
                    "Safe zones can be overrun. When a police zone falls, officers fall back to a military zone.",
                    "New Safe Zone tool: tap anywhere to order one. The Erase tool on a zone's centre closes it.",
                    "Radio feed on screen. Tap a message to jump the camera there. Can be turned off in Settings.",
                    "Street names, callsigns (Unit 14, Bravo-2), phone and radio icons above people, and 911 markers on the map.",
                    "New sounds: phones ringing and radio chatter.",
                    "Games now start with the Move tool selected.",
            },
            {
                    "1.2  -  Menus, sound and new maps",
                    "Main menu with a live zombie city running in the background.",
                    "Pause menu: resume, start a new game, open settings or go back to the main menu.",
                    "Settings: music and sound volume, 3D buildings, blood, health bars, screen shake, FPS counter and max population. Saved between sessions.",
                    "Music: a dark ambient theme for the menus and a tense track while you play.",
                    "Sound effects: pistols, rifles, explosions, bites, zombie groans and screams, panned by where they happen on screen.",
                    "New Game screen with 8 map presets: Classic, Downtown, Suburbs, Industrial, Riverside, Island, Parkland and Night City.",
                    "Custom cities: map size, building style, density, building height, parks, water, traffic, time of day and the starting number of civilians, cops, military and zombies.",
                    "New building styles: suburban houses with pitched roofs and yards, and warehouses with loading yards and roll-up doors.",
                    "Rivers with bridges, and island maps surrounded by beaches and ocean. Zombies can't swim.",
                    "Sunset and night modes. At night, street lamps glow, windows light up and muzzle flashes light the streets.",
                    "Skyscrapers up to 22 floors in the Downtown preset.",
                    "This patch notes log.",
            },
            {
                    "1.1  -  GTA 2 style buildings",
                    "Buildings have real height: walls lean away from the middle of the screen as you move around.",
                    "Windows on every floor, some lit, plus glass shopfronts at street level.",
                    "Downtown towers up to 13 floors; taller buildings cast longer shadows.",
                    "Tree canopies stand above the ground and can hide people underneath.",
                    "Portrait mode: the game now follows your phone's rotation.",
            },
            {
                    "1.0  -  First release",
                    "Procedurally generated city with roads, parks, plazas and parking lots.",
                    "Spawn civilians, cops, military, zombies, runners and brutes.",
                    "Zombie bites infect; anyone killed by a zombie rises again.",
                    "Cops and soldiers hunt zombies; soldiers throw grenades at crowds.",
                    "Bomb and erase tools, follow cam, pause, speed and brush size.",
            },
    };

    private PatchNotes() {
    }
}
