package com.instantaxtion.zombiesandbox;

/** The in-game patch notes log, newest version first. */
final class PatchNotes {
    static final String VERSION = "4.2";
    static final int VERSION_CODE = 17;

    /** Each entry: a heading, then one line per change. */
    static final String[][] NOTES = {
            {
                    "4.2  -  Performance",
                    "Fixed the big slowdown from 4.0: people's daily errands were working out a brand new route across the whole city almost every frame. They now visit a set of popular places whose routes are remembered, and only a few new routes are planned each second. The simulation runs about 15 times faster in a busy city.",
                    "On a slow phone, high game speeds now run a little slower instead of making every frame take longer and longer.",
                    "Far less drawing when zoomed out: windows, legs, hair, soft shadows and shading are only drawn when you're close enough to see them, and vehicles off screen aren't drawn at all.",
                    "The minimap draws its dots a few times a second instead of every frame.",
            },
            {
                    "4.1  -  Realistic graphics",
                    "New Graphics setting: Realistic (the new default) or Classic (the old flat look). It switches straight away, even mid-game.",
                    "Realistic ground: grainy, patched tarmac, raised kerbs with a lit edge and a shadow on the road, paving slabs in slightly different shades, mown stripes on the lawns and more natural colours.",
                    "Soft lighting: buildings darken the ground right around them, their shadows have soft edges, and roofs are weathered with grime, stains and a lit parapet.",
                    "Walls are darker near the ground with a lit cornice along the top, and windows reflect the sky and have sills.",
                    "Leafy tree canopies made of several clumps, shaded underneath and lit on top.",
                    "People are lit from above with soft shadows; cars have a sheen along the roof, darker sides, an outline and wing mirrors.",
                    "The map is smoothed instead of pixelated when you zoom in.",
            },
            {
                    "4.0  -  The big one",
                    "(Games saved in older versions can't be loaded, because cities are built differently now.)",
                    "New zombies: Spitters hang back and lob acid that leaves burning puddles. Bloaters are slow and swollen, and burst into a cloud of infectious gas when they die (police and soldiers try not to shoot them when people are close).",
                    "New police: riot police with shields that turn away most bites from the front, and K9 units (an officer with a police dog). Tap the Cop button again to switch.",
                    "New events: an airstrike (a jet makes a bombing run across the spot you tap), a city alarm (sirens send everyone indoors or to a safe zone) and Infect (someone at that spot is bitten). New Place item: a medkit that patches up anyone nearby and can treat fresh bites.",
                    "Army checkpoints: soldiers check everyone coming into a military safe zone for bites. Most are caught: they are treated in quarantine if a medic is about, otherwise turned away and sent to the hospital.",
                    "Police roadblocks: when the police open a safe zone they park cruisers across the roads leading to it, lights on. They pack up when the zone closes.",
                    "Drag to select: with the Orders tool, drag a box to select a whole group of police and soldiers at once.",
                    "8x speed. Three save slots (plus the autosave) with a Load Game button on the main menu. A Radio Log with every message this game; tap one to go there. Hide Buttons in the pause menu for clean screenshots.",
                    "Name tags setting shows everyone's name. The stats screen graphs police and army numbers too, lists the top killers and where the outbreak started, and Patient Zero is marked on the map.",
                    "The minimap shows where the infection is spreading. Every city has a name.",
                    "Graphics: everything casts shadows the same way, people walk with their legs and have hair, caps and beanies, cars have tyres, brake lights and a glint on the windscreen, trees sway in the breeze, and roofs have solar panels, rooftop gardens and skylights.",
                    "Effects: acid puddles, bloater gas, puffs of dust where bullets hit, a jet with its contrail and shadow, and emergency lights that wash the road red and blue.",
                    "New sounds: the jet, spitting, a bloater bursting, the city alarm and bites glancing off riot shields.",
                    "New in the city: roundabouts, trees along the pavements, back alleys with bins and dumpsters, building sites with a crane, a shopping mall, a football stadium, a power station, a helipad and ambulance bay at the hospital, bandstands and flower beds in parks, and farms on the edge of town.",
                    "Smarter zombies: they see a long way in front of them but only notice what is close behind, remember where they last saw someone and search around there, and their moans draw in other zombies nearby.",
                    "Smarter civilians: everyone has a home. While the city is calm they run errands to the shops, the mall, church or school and go home again; once they hear about the outbreak they head home and lock the door.",
                    "Smarter police and soldiers: they radio sightings to units nearby, move in a wedge behind their leader, advance by bounding (half the squad covers while the other half moves), send flankers round the side for a clear shot, and pull back to a medic when badly hurt. Police form a cordon around the scene of a call.",
                    "Medics do triage: fresh bites first, then the worst hurt. Anyone they cure is pointed to a safe zone.",
            },
            {
                    "3.1  -  Streets, not grids",
                    "Cities are laid out a new way: a few main roads, then each district is split up by its own streets. Streets rarely line up across a main road, so you get offset crossings, T-junctions and blocks of every size instead of a grid. Downtown blocks are small, the suburbs have long ones.",
                    "Block corners are rounded off with wide kerbs, and every street has its own name (lanes, courts, drives and avenues), with a ring road around the edge of town.",
                    "The railway only has level crossings where streets meet it from both sides.",
                    "Fixed: the counts at the top go up straight away when you spawn someone, even while paused.",
                    "Zombies claw at tanks and can knock them out (the crew bails out). Tanks no longer shoot through buildings.",
                    "Fire stations and the hospital don't send anyone out while zombies are at their door.",
                    "People remember where they saw a zombie: civilians keep away from that area for a while, and police and soldiers go and check it out.",
                    "Army trucks and police cars stop short of a big crowd of zombies and let the troops out, instead of driving into it.",
                    "Anyone who gets stuck (brutes at doorways especially) steps aside and tries another way.",
                    "Safe zones stand down after a couple of quiet minutes, or when no one is left to guard them. New zones only open while there are live 911 calls.",
            },
            {
                    "3.0  -  A bigger, truer city",
                    "Bigger maps: Small is now what Medium was, and Large is bigger than ever. (Games saved in older versions can't be loaded, because cities are built differently now.)",
                    "More realistic cities: short blocks downtown and long ones further out, main roads every few streets, an office core ringed by apartments, shops along the main roads, homes on the outskirts and an industrial district on one side of town.",
                    "Suburban cul-de-sacs with houses round a turning circle, and street furniture: benches, bins, fire hydrants, bus stops and traffic lights.",
                    "Railways: a line runs across most maps with level crossings, a station, and trains that pass through (traffic waits for them; anything left on the tracks gets hit).",
                    "Tap anyone to see who they are: their name, job, what they're doing, health, ammo, kills, and who they're with.",
                    "Place tool: drop in a car, a police car, a tank, a fire engine, barricades (drag to build a line; zombies batter them down), a supply crate or a fire.",
                    "Events tool: send a horde in from the edge of town, start a panic, trigger an outbreak inside a building, call a supply drop or bring in a raider gang.",
                    "Undo takes back your last placement or spawn. Clear now asks what to clear: everyone, zombies only, bodies and blood, wrecks and fires, or barricades.",
                    "Raiders: armed gangs who shoot zombies and police, rob armed civilians of their guns and loot shops. Police treat them as a threat. Tap the Civilian button again to spawn them.",
                    "Zombie dogs: dogs killed by zombies can come back as fast, vicious zombie dogs. Fresh zombies are quicker for their first minute, and during a long outbreak the infection evolves and new zombies get tougher.",
                    "Survivors act on their own: families make supply runs to the shops, armed civilians form patrols, and people running for their lives jump into abandoned cars and drive off. Some outbreaks start inside buildings.",
                    "Recovery: once the zombies are gone the city recovers. Volunteers clear away the bodies, buildings are repaired, wrecks are towed and the safe zones close.",
                    "Music follows the action: calm when the streets are quiet, intense in a big fight. New sounds for trains, tanks, machine guns, snipers, collapses, crashes, fire hoses and ambulances.",
                    "Minimap (tap it to jump there) and an Auto cam that follows the most interesting thing going on.",
                    "Screenshots: save a picture of your city from the pause menu and share it.",
                    "Records and achievements, kept across games, in the main menu.",
                    "New settings: text and button size, battery saver and minimap. A new app icon.",
            },
            {
                    "2.4  -  Volunteers",
                    "Recruitment: once the outbreak has cost the police or army people, they put a call out on the radio for volunteers to fill the gaps (only as many as they've lost, and only while the station or base is safe).",
                    "Civilians decide for themselves. Most say no. People who own a gun are keen, and people with family to look after or who are hurt usually refuse. Anyone who says no isn't asked again.",
                    "Volunteers walk to the precinct or base, train for a few seconds and come out as a cop or soldier. Scared volunteers turn back if zombies show up on the way.",
                    "The stats panel and Stats screen show how many joined and how many said no.",
            },
            {
                    "2.3  -  Armor, ambulances and a new setup screen",
                    "New Game screen redesigned: a live preview of the city, map cards with a description of each map, one-tap buttons for every option, and a New map button to reroll the city before you start.",
                    "Two new maps: Metropolis (a huge dense skyline with three precincts and a base) and Village (cottages among fields, far from help).",
                    "New buildings: apartment blocks (rooftop water tanks and washing lines, room for lots of people to hide), parking garages (cars parked on the top deck) and pharmacies (hurt people stop in to patch themselves up).",
                    "New vehicles: tanks roll out of the base for big hordes, shelling crowds and machine-gunning stragglers, and ambulances drive out from the hospital to fetch the badly hurt.",
                    "New military: a commander (beret, pistol and radio) whose soldiers shoot better when he's close and who calls in armor or air support, snipers with long-range scoped rifles, and machine gunners in every squad. Tap the Military button again to pick which one to spawn.",
                    "The helicopter now starts up on the helipad, takes off, drops lower to give its gunner a shot, flies home and lands. It leans into turns and its shadow moves away as it climbs.",
                    "Every vehicle shows what it's doing: responding, carrying a squad, fighting a fire, loading a patient, driving people to safety, broken down and so on.",
                    "Fixed: people hiding in buildings walk around to the door instead of running into the wall.",
                    "Fixed: parked cars stay against the kerb, and cars abandoned in traffic roll over to the side of the road.",
                    "New effects: spent shell cases fly out of guns, muzzle flashes light the ground, explosions throw out debris, tyres leave skid marks, rotor wash kicks up dust, and fire hoses leave puddles.",
                    "New textures: patched and cracked asphalt, manhole covers, worn paving slabs, grass tufts and wildflowers.",
                    "Higher limits: up to 800 civilians, 60 cops, 40 soldiers and 200 zombies at the start, and a max population of up to 6000 in Settings.",
            },
            {
                    "2.2  -  Wrecks, rubble and smarter survivors",
                    "Cars take damage: running over zombies, crashing into each other, gunfire, explosions and zombies clawing at them. Damaged cars smoke and slow down, then break down. Everyone inside gets out, and some wrecks catch fire.",
                    "Fire engines: fire stations send an engine to burning cars and gas pumps. The crew hoses the fire down and pulls out if zombies close in.",
                    "Destructible buildings: bombs, grenades and blasts crack and scorch buildings, and enough of them bring one down in a cloud of dust. Anyone inside or next to it gets hurt.",
                    "Bullet holes and scorch marks build up on walls after a firefight.",
                    "See-through roofs: zoom right in and roofs and walls fade so you can see the rooms, furniture and anyone hiding inside.",
                    "Bird's-eye view: a new View button (and setting) switches between the leaning 3D buildings and a flat view straight down.",
                    "Dogs: people walk their dogs, and dogs bark at zombies and go for them to protect their owner. Tap the Civilian button again to spawn dogs.",
                    "Families and friends walk together, stay together when they run, hide in the same building and pull zombies off each other.",
                    "Traffic: people running for their lives wave down passing cars and jump in. Drivers take them to a safe zone if there is one. Zombies chase cars and swarm the ones that stop.",
                    "Zombie hordes: idle zombies gather behind a leader and roam the city, merging into bigger hordes. The radio warns when a big one is on the move.",
                    "Smarter zombies spread out to surround people and stop to feed on the dead.",
                    "Smarter police and soldiers: they shoot the zombie that is attacking someone (or a runner or screamer) first, hold fire when a person is in the way, don't throw grenades near people, fall back when swarmed or reloading, and soldiers keep their squad together.",
                    "Smarter civilians: panic spreads through a crowd, people run towards nearby cops and soldiers, and armed civilians back off while they shoot.",
                    "Churches, schools and supermarkets can become safe zones. Supermarkets also stock ammo, and armed civilians go there to restock.",
                    "City codes: every city has a code (shown in the pause menu and stats). Use City code on the New Game screen to replay a city or play one a friend shared.",
                    "Burnt-out wrecks, collapsed buildings, damage and families are now kept in saved games.",
                    "Map labels no longer hide under the radio feed or the stats panel.",
            },
            {
                    "2.1  -  A living city",
                    "New buildings: rows of shops with striped awnings, gas stations, churches with steeples and churchyards, schools, fire stations with fire trucks, and supermarkets with big car parks. People can hide in the shops, churches, schools and supermarkets.",
                    "New parks: playgrounds, soccer fields, basketball and tennis courts, community gardens, skateparks and cemeteries.",
                    "New maps: Old Town (narrow streets, shops and churches), Small Town and Campus (schools and sports fields). Every map has its own mix of landmarks and parks.",
                    "Traffic: cars drive around town, brake for pedestrians, plough through zombies, and get abandoned when the driver is surrounded.",
                    "Pigeons in the parks and plazas scatter at gunfire, explosions or anyone walking up, and land somewhere else.",
                    "Fires: explosions set parked cars burning, sometimes blowing up a moment later. Gas pumps go up in a big secondary blast. Wrecks stay charred, and fire hurts anyone standing in it.",
            },
            {
                    "2.0  -  The city fights back",
                    "Police cruisers drive backup officers to incidents and army trucks carry reserve squads out of the base, running over zombies on the way.",
                    "Air support: a helicopter flies from the base helipad and circles the fight with a door gunner. Sorties are limited.",
                    "Civilians barricade themselves in homes, offices and warehouses. Zombies batter the doors down, and people come out once the street is quiet. If someone infected turns inside, the building is lost.",
                    "Guards stand at the police station doors and the base gates.",
                    "Some civilians own a gun, and anyone can pick up a weapon dropped by a fallen cop or soldier.",
                    "Ammo is limited. Units out of ammo radio in and head back to the station or base to resupply.",
                    "Hand-to-hand: anyone can shove a zombie away and stun it, and cops and soldiers hit back with their weapon.",
                    "Medics and a hospital: medics heal the hurt and can cure fresh bites. Badly hurt people walk to the hospital.",
                    "Zombies are drawn to gunfire and explosions. New types: crawlers (hard to hit, and what's left after a blast) and screamers (their shriek calls every zombie nearby).",
                    "Orders tool: tap a cop or soldier (soldiers bring their whole squad), then tap where to send them. Tap them again to release them.",
                    "Save and load: save from the pause menu. The game also saves itself when you leave, and Continue picks it up.",
                    "Stats screen: people vs zombies over time, plus totals.",
                    "How to Play: a short tutorial on the first game, and in the main menu any time.",
                    "The stats panel collapses with a tap, the radio feed is shorter on phones, and people are easier to tell apart when zoomed out.",
                    "The Zombie button covers all zombie types: tap it again to switch.",
            },
            {
                    "1.6  -  Simpler cities",
                    "Water is gone: no more rivers, islands, ponds or fountains. Plazas have statues instead.",
                    "It's always daytime. The sunset and night modes (and the orange haze) are removed.",
                    "The New Game screen is down to 7 options: map, map size, civilians, cops, military, zombies and reinforcements.",
                    "Maps: Classic, Downtown, Suburbs, Industrial and Parkland. Each one decides its own buildings, street layout, parks, police stations and military base.",
            },
            {
                    "1.5  -  Limits",
                    "Safe zones have a capacity: 25 in a park zone, 35 at a police station, 40 for a military zone and 60 at a base. Labels show how full each one is.",
                    "Full zones radio that they're turning people away, and civilians head for a zone with room or keep running.",
                    "Reinforcements are now a small, fixed reserve that never refills. Choose Off, Low, Medium or High on the New Game screen (Medium: 2 backup waves of officers and 2 army squads of 4).",
                    "The stats panel shows the reserves left, and the radio says when the last one is sent.",
                    "Ponds no longer cut through park footpaths.",
                    "Rivers keep a grassy bank: no building stands on or right next to the water.",
            },
            {
                    "1.4  -  Less grid, more city",
                    "New Street layout option: Grid, Varied or Organic.",
                    "Varied and Organic cities merge some blocks into superblocks, so streets have T-junctions and blocks come in different sizes.",
                    "Boulevards: wide avenues with a tree-lined median.",
                    "Rivers now wind across the map instead of running straight. Roads cross on bridges, and riverside buildings make way for parks.",
                    "Islands have a rounded, irregular coastline with beaches. Roads end at the sand.",
                    "Parks can have ponds and curved footpaths.",
                    "Rounded curbs at block corners.",
                    "Police stations: a precinct with parked cruisers. Some cops start there, backup officers leave from there, and police set up their safe zone there first.",
                    "Military bases: a fenced compound with gates, barracks, a helipad, tents, a watchtower and army trucks. Soldiers start on base, squads deploy from its gate, and the base becomes the military safe zone.",
                    "Idle soldiers return to base when there's nothing to fight.",
                    "New Game options for the number of police stations (0-3) and a military base.",
            },
            {
                    "1.3  -  911, radio and safe zones",
                    "911 calls: civilians who spot zombies call it in. Dispatch opens an incident at the nearest street corner and sends the closest free cops.",
                    "Cops report when they're en route, on scene and when the area is clear. Dispatch calls it in when an officer goes down.",
                    "Police and military talk on the radio: big incidents, downed officers or a safe zone under attack make police request military support, and the military sends a squad.",
                    "Reinforcements: if nobody is free, backup officers or a military squad arrive from the edge of the map. Can be turned off on the New Game screen.",
                    "Safe zones: police and military set up guarded zones with sandbags in parks, plazas and parking lots. Guards take posts around the edge and face outward.",
                    "Civilians run to safe zones when they're scared or hear about one on the news, and shelter inside.",
                    "Safe zones can be overrun. When a police zone falls, officers fall back to a military zone.",
                    "New Safe Zone tool: tap anywhere to order one. The Erase tool on a zone's centre closes it.",
                    "Radio feed on screen. Tap a message to jump the camera there. Can be turned off in Settings.",
                    "Street names, callsigns (Unit 14, Bravo-2), phone and radio icons above people, and 911 markers on the map.",
                    "New sounds: phones ringing and radio chatter.",
                    "Games now start with the Move tool selected.",
            },
            {
                    "1.2  -  Menus, sound and new maps",
                    "Main menu with a live zombie city running in the background.",
                    "Pause menu: resume, start a new game, open settings or go back to the main menu.",
                    "Settings: music and sound volume, 3D buildings, blood, health bars, screen shake, FPS counter and max population. Saved between sessions.",
                    "Music: a dark ambient theme for the menus and a tense track while you play.",
                    "Sound effects: pistols, rifles, explosions, bites, zombie groans and screams, panned by where they happen on screen.",
                    "New Game screen with 8 map presets: Classic, Downtown, Suburbs, Industrial, Riverside, Island, Parkland and Night City.",
                    "Custom cities: map size, building style, density, building height, parks, water, traffic, time of day and the starting number of civilians, cops, military and zombies.",
                    "New building styles: suburban houses with pitched roofs and yards, and warehouses with loading yards and roll-up doors.",
                    "Rivers with bridges, and island maps surrounded by beaches and ocean. Zombies can't swim.",
                    "Sunset and night modes. At night, street lamps glow, windows light up and muzzle flashes light the streets.",
                    "Skyscrapers up to 22 floors in the Downtown preset.",
                    "This patch notes log.",
            },
            {
                    "1.1  -  GTA 2 style buildings",
                    "Buildings have real height: walls lean away from the middle of the screen as you move around.",
                    "Windows on every floor, some lit, plus glass shopfronts at street level.",
                    "Downtown towers up to 13 floors; taller buildings cast longer shadows.",
                    "Tree canopies stand above the ground and can hide people underneath.",
                    "Portrait mode: the game now follows your phone's rotation.",
            },
            {
                    "1.0  -  First release",
                    "Procedurally generated city with roads, parks, plazas and parking lots.",
                    "Spawn civilians, cops, military, zombies, runners and brutes.",
                    "Zombie bites infect; anyone killed by a zombie rises again.",
                    "Cops and soldiers hunt zombies; soldiers throw grenades at crowds.",
                    "Bomb and erase tools, follow cam, pause, speed and brush size.",
            },
    };

    private PatchNotes() {
    }
}
